name: "PWA Native Build Action"
description: "Creates a Wails.io binary wrapping a PWA"

inputs:
  pwa-build:
    description: "Compiled static files"
    required: true
    default: "true"
  build-name:
    description: "The name of the binary file"
    required: true
  build-platform:
    description: "Platform to build for"
    required: false
    default: "darwin/universal"

runs:
  using: "composite"
  steps:
    # Setup and configure GoLang
    - name: Setup GoLang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    # Setup and configure NodeJS
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 16
    # install wails
    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      shell: bash
    - name: Install Linux Wails deps
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
      shell: bash
    # Building step
    - name: Turn Source repo into Wails Application
      shell: bash
      run: |
        cd ..
        wails generate template -frontend ${{ inputs.pwa-build }} -name ${{inputs.build-name}}
        wails init -t ${{inputs.build-name}} -g -d build-native -n ${{inputs.build-name}}
        mv ${{ github.workspace }} ../workspace && mkdir "${{ github.workspace }}"
        mv build-native/* ${{ github.workspace }}
        cd ${{ github.workspace }}
    - name: Build
      uses: dAppServer/wails-build-action@main
      with:
        build-name: ${{inputs.build-name}}
        build-platform: ${{inputs.build-platform}}

