name: Lethean Desktop build
permissions:
  contents: write
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          { name: Lethean, platform: linux/amd64, os: ubuntu-latest },
          { name: Lethean, platform: windows/amd64, os: windows-latest },
          { name: Lethean, platform: darwin/universal, os: macos-latest }
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          path: frontend
          repository: 'letheanVPN/lthn-app-desktop'
          submodules: recursive
      - uses: dAppServer/pwa-native-action@main
        with:
          pwa-build: frontend
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
      # Upload build assets
      - uses: actions/upload-artifact@v2
        with:
          name: Build ${{runner.os}} ${{ matrix.build.name }}
          path: |
            native/build/bin/
            native\build\bin\*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            native/build/bin/*
