name: Desktop build
permissions:
  contents: write
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/pwa-native-action@main
        with:
          build-name: lethean
          build-platform: linux/amd64



